name = "raidhack-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[env.development]
vars = { ENVIRONMENT = "development", JWT_SECRET = "dev-secret-key-for-testing" }

[env.production]
vars = { ENVIRONMENT = "production" }

# データベース設定
[[d1_databases]]
binding = "DB"
database_name = "raidhack-db"
database_id = "351ec61c-6b58-448f-a888-c9df33a3045f"

[vars]
# 本番環境でも使用する変数
CORS_ORIGIN = "*"
