name: Deploy RAIDHack – Production

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    name: Deploy Workers API (prod)
    outputs:
      api-url: ${{ steps.deploy-api.outputs.api-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install API dependencies
        run: |
          cd api
          npm ci

      - name: Deploy Workers API
        id: deploy-api
        run: |
          cd api
          WORKER_NAME="raidhack-api"
          API_URL="https://raidhack-api.ukawamochi5.workers.dev"
          echo "Deploying to: $API_URL"
          npx wrangler deploy --minify --name "$WORKER_NAME"
          echo "api-url=$API_URL" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-web:
    runs-on: ubuntu-latest
    name: Deploy Pages (prod)
    needs: deploy-api
    outputs:
      pages-url: ${{ steps.deploy-pages.outputs.pages-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install Web dependencies
        run: |
          cd web
          npm ci

      - name: Build React app
        run: |
          cd web
          npm run build
        env:
          VITE_API_BASE: ${{ needs.deploy-api.outputs.api-url }}

      - name: Deploy to Cloudflare Pages (production)
        id: deploy-pages
        run: |
          cd web
          PROJECT_NAME="raidhack-web"
          echo "Deploying to production"
          output=$(npx wrangler@latest pages deploy dist --project-name "$PROJECT_NAME" --compatibility-date "2024-01-15" 2>&1)
          PAGES_URL="https://raidhack-web.pages.dev"
          echo "$output"
          actual_url=$(echo "$output" | grep -oE 'https://[a-zA-Z0-9\-\.]+\.pages\.dev' | head -1)
          if [ -n "$actual_url" ]; then
            PAGES_URL="$actual_url"
          fi
          echo "pages-url=$PAGES_URL" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}